<div id="owl-home-banner" class="owl-carousel owl-theme-home owl-theme-cod1">
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/home-slider1.jpg')?>" alt="Zuriel Homes"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/home-slider1.jpg')?>" alt="Zuriel Homes"></div>
</div>
<script>
	jQuery(document).ready(function() {

		jQuery("#owl-home-banner").owlCarousel({

			navigation : true, // Show next and prev buttons
			slideSpeed : 300,
			paginationSpeed : 400,
			singleItem:true
			// "singleItem:true" is a shortcut for:
			// items : 1,
			// itemsDesktop : false,
			// itemsDesktopSmall : false,
			// itemsTablet: false,
			// itemsMobile : false

		});
		jQuery('.owl-next').html('<span class="fa fa-angle-right"></span>');
		jQuery('.owl-prev').html('<span class="fa fa-angle-left"></span>');
	});
</script>