<div id="owl-home-banner" class="owl-carousel owl-theme-home">
	<div class="item"><img src="http://owlgraphic.com/owlcarousel/demos/assets/fullimage1.jpg" alt="The Last of us"></div>
	<div class="item"><img src="http://owlgraphic.com/owlcarousel/demos/assets/fullimage2.jpg" alt="GTA V"></div>
	<div class="item"><img src="http://owlgraphic.com/owlcarousel/demos/assets/fullimage3.jpg" alt="Mirror Edge"></div>
</div>
<style>
	#owl-home-banner .item img{
		display: block;
		width: 100%;
		height: auto;
	}
	.owl-theme-home .owl-buttons
	{
		position: absolute;
		top: 45%;
		width: 100%;
	}
	.owl-theme-home .owl-buttons .owl-prev
	{
		float: left;
	}
	.owl-theme-home .owl-buttons .owl-next
	{
		float: right;
	}
</style>
<script>
	jQuery(document).ready(function() {

		jQuery("#owl-home-banner").owlCarousel({

			navigation : true, // Show next and prev buttons
			slideSpeed : 300,
			paginationSpeed : 400,
			singleItem:true
			// "singleItem:true" is a shortcut for:
			// items : 1,
			// itemsDesktop : false,
			// itemsDesktopSmall : false,
			// itemsTablet: false,
			// itemsMobile : false

		});

	});
</script>