<div id="owl-home-brand" class="owl-carousel owl-theme-cod1 owl-theme-brands">
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
	<div class="item"><img src="<?php echo $this->getSkinUrl('images/home/brands.png')?>" alt="The Last of us"></div>
</div>
<script>
	jQuery(document).ready(function() {
		jQuery("#owl-home-brand").owlCarousel({
			autoPlay: 3000, //Set AutoPlay to 3 seconds
			items : 4,
			itemsDesktop : [1199,3],
			itemsDesktopSmall : [979,3],
		});
	});
</script>
