<div id="owl-home-brand" class="owl-carousel owl-theme-cod1">
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
	<div class="item"><img src="http://placeholder.it/250x250" alt="The Last of us"></div>
</div>
<script>
	jQuery(document).ready(function() {
		jQuery("#owl-home-brand").owlCarousel({
			autoPlay: 3000, //Set AutoPlay to 3 seconds
			items : 4,
			itemsDesktop : [1199,3],
			itemsDesktopSmall : [979,3],
		});
	});
</script>
