<div class="how-it-works">
	<h1>HOW IT WORKS</h1>
	<ul class="steps">
		<li><h6>Buy Products</h6></li>
		<span class="arrow-right"></span>
		<li><h6>Book Appointment</h6></li>
		<span class="arrow-right"></span>
		<li><h6>Deleivery & Installation</h6></li>
		<span class="arrow-right"></span>
		<li><h6>Make Payment COD or Card</h6></li>
		<span class="arrow-right"></span>
		<li><h6>You are satisfied</h6></li>
	</ul>
</div>