<div class="how-it-works">
	<div class="inner">
		<h1>HOW IT WORKS</h1>
		<ul class="steps">
			<li class="step1"><h6>Buy Products</h6></li>
			<span class="arrow-right fa fa-angle-right"></span>
			<li class="step2"><h6>Book Appointment</h6></li>
			<span class="arrow-right fa fa-angle-right"></span>
			<li class="step3"><h6>Deleivery & Installation</h6></li>
			<span class="arrow-right fa fa-angle-right"></span>
			<li class="step4"><h6>Make Payment COD or Card</h6></li>
			<span class="arrow-right fa fa-angle-right"></span>
			<li class="step5"><h6>You are satisfied</h6></li>
		</ul>
	</div>
</div>