<?php $wid=$this->getTestimonialsImageWidth(); ?>
<?php $hei=$this->getTestimonialsImageHeight(); ?>
<?php $faceimg=$this->getTestimonialsImages(); ?>
<?php $_mediaPath = Mage::getBaseUrl('media');
$imgr=str_replace('/index.php', '', $img); ?>
<?php
$_testimonials = Mage::getModel('testimonials/testimonials')->getCollection();
if(count($_testimonials) > 0):
?>
<div class="testimonials">
	<h1>TESTIMONIALS</h1>
	<h6>WHAT OUR CUSTOMER SAYS</h6>
	<div id="owl-home-testimonials" class="owl-carousel">
		<?php foreach($_testimonials as $testimonial){
			for($i=0;$i<10;$i++) {
				$_img = $_mediaPath . $testimonial->getPic();
				?>
				<div class="item">
					<div class="profile">
						<img src="<?= $_img ?>" width="<?php echo $wid; ?>" height="<?php echo $hei; ?>">
						<h5><?php echo $testimonial->getName(); ?></h5>
						<span>Satisfied Customer</span>
					</div>
					<div class="quotes">
						<p>"<?php echo $testimonial->getMessage(); ?>"</p>
					</div>
				</div>
				<?php
			}
		} ?>
	</div>
</div>
<script>
	jQuery(document).ready(function() {
		jQuery("#owl-home-testimonials").owlCarousel({
			slideSpeed : 300,
			paginationSpeed : 400,
			singleItem:true
			// "singleItem:true" is a shortcut for:
			// items : 1,
			// itemsDesktop : false,
			// itemsDesktopSmall : false,
			// itemsTablet: false,
			// itemsMobile : false

		});

	});
</script>
<?php endif;?>